### ISSUE TITLE
Basic brushes should use an abreviation to keep their names short.

### ISSUE THREAD

**Issue by Spirou4D** [LoganFairbairn/matlayer#112]
When you create brushes: use short initials for the name because don't see the title in the menu! Like that ML_EraseHard and not Matlayer_EraseHard, please.

**Comment by LoganFairbairn** [comment]
This is a good idea that's a better format in general. Added to the project board.

**Comment by LoganFairbairn** [comment]
I've renamed imported assets (brushes and group nodes) with an abbreviated prefix.
