### ISSUE TITLE
Blender MeshMap Preview: exiting loses some settings

### ISSUE THREAD

**Issue by JBreckeen** [LoganFairbairn/matlayer#147]
Morning!

First let me say I love the MeshMap Preview!  It is such a quick and easy way to view/tweak the maps.

The one thing that is odd, is that when you exit the Preview it always switches back to defaults.  

I see this in two ways:  first thing is that when you exit the Preview, it always switches back to EEVEE (though not a big deal at all), even when I had Cycles selected, and Cycles is selected in the "Viewport" tab in MatLayer.

Also, it also removes the active material from the object after you exit the Preview.  This could be a bit more of an issue if that a user did not have a Fake User on the material, uses the Preview, then saves the file.  That material could be lost.

I would think this is usually not an issue since you would tend to generate the MeshMaps before moving forward on the surfacing, but it still can be a gotcha.  I sometimes use a simple "fake" holding material while I model, which then gets unconnected when doing the MeshMap Preview.   

Thanks again.

JRB.

**Comment by LoganFairbairn** [comment]
Hi, thanks for reporting this issue. I'll look into this.

**Comment by LoganFairbairn** [comment]
Heyo, this is fixed on main branch now.

When you toggle the mesh map preview on, it will cache the names of the materials in the object's data. When you toggle the preview off, it will re-apply the materials that were on the object before your toggled the mesh map preview on (as long as those materials still exist).

The render engine, and viewport shading mode will also be cached when you initially toggle the material channel on, and then re-applied when you toggle the preview off.

I should mention 2.0.3 comes with many updates to the core materials. This means MatLayer materials made in 2.0.2 will cause errors if accessed with MatLayer 2.0.3. This lack of backwards compatibility was necessary for the next release, but I'll be attempting to preserve backwards compatibility for following versions.
