### ISSUE TITLE
Error when trying to import a texture set if the active material is not created with Matlayer.

### ISSUE THREAD

**Issue by frkntlr** [LoganFairbairn/MatLayer#159]
If no materia is created or even if a random material is created, it gives an error if the texture is not created with the matte layer.

Instead of giving an error, the plugin should be able to create material and import textures into it.
For example, the created texture nomenclature; Let it be a name like Wood_Color. Hang the part before the _ of this name. so that we get the material named Wood.
 
[](https://github.com/LoganFairbairn/MatLayer/assets/14142761/9b35fed0-d386-4561-864f-06204344824c)

Error Code;
`bpy.ops.matlayer.import_texture_set(filepath="/home/username/Images/PBR/Fabric062_4K-JPG/Fabric062_4K-JPG_Roughness.jpg", files=[{"name": "Fabric062_4K-JPG_Roughness. jpg", "name":"Fabric062_4K-JPG_Roughness.jpg"}, {"name":"Fabric062_4K-JPG_NormalGL.jpg", "name":"Fabric062_4K-JPG_NormalGL.jpg"}, {"name":"Fabric062_4K-JPG_NormalDX. jpg", "name":"Fabric062_4K-JPG_NormalDX.jpg"}, {"name":"Fabric062_4K-JPG_Displacement.jpg", "name":"Fabric062_4K-JPG_Displacement.jpg"}, {"name":"Fabric062_4K-JPG_Color. jpg", "name": "Fabric062_4K-JPG_Color.jpg"}, {"name": "Fabric062_4K-JPG_AmbientOcclusion.jpg", "name": "Fabric062_4K-JPG_AmbientOcclusion.jpg"}])`

**Comment by LoganFairbairn** [comment]
Thanks for the report, I'll look into this as soon as I can. I'm currently working on version 3 of MatLayer which brings some major internal code changes to support the ability to use custom 'shader' node setups, mostly to support NPR shaders.

**Comment by LoganFairbairn** [comment]
I added additional context polling so it's no longer possible to call import texture set, when the active material isn't created with the add-on.
