### ISSUE TITLE
Cannot open folder because os.startfile is a windows-only function

### ISSUE THREAD

**Issue by muhuk** [LoganFairbairn/MatLayer#162]
`bpy.ops.matlayer.open_mesh_map_folder` command fails on Linux becuase `startfile` is a windows-only function.

https://github.com/LoganFairbairn/MatLayer/blob/427cb9c007766128ea6737b7b70915aad264a2be/core/blender_addon_utils.py#L547

**Comment by LoganFairbairn** [comment]
Thanks, I wasn't aware of this issue. I'm working on MatLayer 3.0 which brings the ability to switch 'shaders' among other features, so I can't address this right away, so I've added this ticket to the projects board.

Cheers !

**Comment by LoganFairbairn** [comment]
This is fixed in version 3.0, available on main branch now.
